In [7]:
import numpy as np
import csv
from typing import List
from dataclasses import dataclass

@dataclass
class Order:
    order_id: int
    route: List[str]

def parse_route(route_str: str) -> List[str]:
    return route_str.split("->")

def load_orders(filename:str) -> List[str]:
    orders: List[Orders] = []
    with open(filename, newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            order_id = int(row['order_id'])
            route = parse_route(row['route'])
            orders.append(Order(order_id=order_id, route=route))
    return orders

In [ ]:
order = ['A','B','D']

fu_to_index = {"A": 0, "B": 1, "C": 2, "D": 3}
time_on = [0, 0, 0, 0]
for fu in order:
    idx = fu_to_index[fu]
    time_on[idx] = 4
print(time_on)

['A', 'B', 'D']
4
4
0
['B', 'C', 'A']
0
0
0
['B', 'C', 'A']
0
0
0
[Order(order_id=1, route=['A', 'B', 'D']), Order(order_id=2, route=['B', 'C', 'A']), Order(order_id=3, route=['B', 'C', 'A'])]


In [33]:

orders = load_orders('sample_order2.csv')
FU_time = 4
FU_order_times = []
FUs = {'A':4, 'B':5, 'C':8, 'D':4}
def time_on(i):
    time_on = [0,0,0,0] 
    for j in range(len(orders[i].route)):   
        idx = fu_to_index[orders[i].route[j]]
        time_on[idx] = FUs[orders[i].route[j]]
    return time_on

for i in range(len(orders)):
    FU_order_times.append(time_on(i))

processing_times = np.array(FU_order_times)

print(processing_times)
print(orders)

[[4 5 0 4]
 [4 5 8 0]
 [4 5 8 0]]
[Order(order_id=1, route=['A', 'B', 'D']), Order(order_id=2, route=['B', 'C', 'A']), Order(order_id=3, route=['B', 'C', 'A'])]


In [32]:
print(processing_times.shape)

(3, 4)
